CONNECT SYSTEM/fakepassword

-- AlphaSort PRIMARY TABLES: -------------------------------------------------------------------------------------------

CREATE TABLE BUREAU (
 REGION VARCHAR2(10) PRIMARY KEY,
 NOMBUREAU VARCHAR2(20) NOT NULL,
 ADRESSE VARCHAR2(40),
 DATECREATION INT
);

CREATE TABLE DIRIGEANT(
 CODE VARCHAR2(5) PRIMARY KEY,
 NOM VARCHAR2(20),
 PRENOM VARCHAR2(20),
 PROFESSION VARCHAR2(20)
);

CREATE TABLE JOUEUR(
 CODE INT PRIMARY KEY,
 NOM VARCHAR2(30),
 PRENOM VARCHAR2(30),
 DATENAISSANCE DATE,
 NATIONNALITE VARCHAR2(30),
 POIDS INT,
 TAILLE INT,
 CLASSE VARCHAR2(10)
);

-- AlphaSort SECONDARY TABLES: -------------------------------------------------------------------------------------------
CREATE TABLE CLUBSPORTIF (
 CODE VARCHAR2(5) PRIMARY KEY,
 NOMCLUB VARCHAR2(50),
 DATECREATION INT,
 DIRIGEANT VARCHAR2(5) REFERENCES DIRIGEANT(CODE),
 VILLE VARCHAR2(30),
 REGION VARCHAR2(10)
);

CREATE TABLE PALMARES (
 CLUB VARCHAR2(5) NOT NULL REFERENCES CLUBSPORTIF(CODE),
 ANNEE VARCHAR2(4) NOT NULL,
 TROPHEE VARCHAR2(30),
 NOMBREMATCHGAGNE INT,
 NOMBREMATCHPERDUS INT,
 PRIMARY KEY (CLUB, ANNEE)
);

CREATE TABLE PERSONNEL(
    CODE VARCHAR(5) PRIMARY KEY,
    NOM VARCHAR2(30),
    PRENOM VARCHAR2(30),
    DATENAISSANCE DATE,
    FONCTION VARCHAR(30),
    REGION VARCHAR2(10),
    VILLE VARCHAR2(20),
    FOREIGN KEY (REGION) REFERENCES BUREAU(REGION)
);

CREATE TABLE STADE(
 CODE VARCHAR2(5) PRIMARY KEY NOT NULL,
 NOM VARCHAR2(30),
 VILLE VARCHAR2(30),
 REGION VARCHAR2(10) REFERENCES BUREAU(REGION),
 CAPACITE INT
);

CREATE TABLE STAFFTECHNIQUE(
    CODE VARCHAR2(5) PRIMARY KEY,
    NOM VARCHAR2(20),
    CLUB VARCHAR2(5) REFERENCES CLUBSPORTIF(CODE),
    FONCTION VARCHAR(20)
);

-- AlphaSort TERTIARY TABLES: ------------------------------------------------------

CREATE TABLE ARBITRE(
 CODE VARCHAR2(5) PRIMARY KEY NOT NULL,
 NOM VARCHAR2(20),
 PRENOM VARCHAR2(20),
 DATENAISSANCE DATE,
 REGION VARCHAR2(10) REFERENCES BUREAU(REGION),
 CLUBPREFERE VARCHAR2(5) REFERENCES CLUBSPORTIF(CODE)
);

CREATE TABLE EQUIPE(
 CLUB VARCHAR2(5) REFERENCES CLUBSPORTIF(CODE),
 JOUEUR INT REFERENCES JOUEUR(CODE),
 DATEDEBUTCONTRAT DATE,
 DATEFINCONTRAT DATE,
 NUMEROMAILLOT INT,
 POSTE VARCHAR(20),
 PRIMARY KEY (CLUB,JOUEUR)
);

CREATE TABLE MATCH(
 CODE VARCHAR2(5) PRIMARY KEY NOT NULL,
 NBREBUTCLUBA INT,
 NBREBUTCLUBB INT,
 NBRESPECTATEURS INT,
 ARBITRE VARCHAR2(5) REFERENCES ARBITRE(CODE),
 STADE VARCHAR2(5) REFERENCES STADE(CODE)
);

-- AlphaSort QUADIARY TABLES: -------------------------------------------------------------------------------------------

CREATE TABLE CALENDRIER(
    MATCH VARCHAR2(5) REFERENCES MATCH(CODE),
    DATEMATCH DATE,
    HEURE TIMESTAMP,
    CLUBA VARCHAR2(5) REFERENCES CLUBSPORTIF(CODE),
    CLUBB VARCHAR2(5) REFERENCES CLUBSPORTIF(CODE),
    STADE VARCHAR2(5) REFERENCES STADE(CODE),
    PRIMARY KEY(MATCH, DATEMATCH)
);
