-- BMASTER ---------------------------------------------------------

CONNECT b_master/b_master
CREATE DATABASE LINK b_masterTosystem
CONNECT TO system IDENTIFIED by fakepassword
using 'localhost:1521/XE';

---- Fragments Independants (AlphaSort)
CREATE TABLE ARBITRE
AS SELECT * FROM system.ARBITRE@b_masterTosystem;

CREATE TABLE BUREAU
AS SELECT * FROM system.Bureau@b_masterTosystem;

CREATE TABLE CALENDRIER_GLOBAL
AS SELECT * FROM system.CALENDRIER@b_masterTosystem;

CREATE TABLE DIRIGEANT
AS SELECT * FROM system.DIRIGEANT@b_masterTosystem;

CREATE TABLE MATCH_GLOBAL
AS SELECT * FROM system.MATCH@b_masterTosystem;

---- Fragments Where (AlphaSort)

CREATE TABLE CLUBSPORTIF
AS select * FROM system.CLUBSPORTIF@b_masterTosystem 
WHERE REGION ='Nord';

CREATE TABLE STADE
AS SELECT * FROM system.STADE@b_masterTosystem
WHERE REGION ='Nord';

CREATE TABLE PERSONNEL
AS SELECT * FROM system.PERSONNEL@b_masterTosystem
WHERE REGION = 'Nord';

---- Fragments Join (AlphaSort)
CREATE TABLE EQUIPE
AS SELECT S.CLUB, S.JOUEUR, DATEDEBUTCONTRAT, DATEFINCONTRAT, NUMEROMAILLOT, POSTE 
FROM system.EQUIPE@b_masterTosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

CREATE TABLE JOUEUR
AS SELECT S.CODE, NOM, PRENOM, DATENAISSANCE, NATIONNALITE, POIDS, TAILLE, CLASSE
FROM system.JOUEUR@b_masterTosystem S JOIN EQUIPE E ON S.CODE = E.JOUEUR;

CREATE TABLE PALMARES
AS SELECT P.CLUB, ANNEE, TROPHEE, NOMBREMATCHGAGNE, NOMBREMATCHPERDUS
FROM system.PALMARES@b_masterTosystem P JOIN CLUBSPORTIF C ON P.CLUB = C.CODE;

CREATE TABLE STAFFTECHNIQUE
AS SELECT S.CODE, NOM, S.CLUB, FONCTION 
FROM system.STAFFTECHNIQUE@b_masterTosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

-- BREGION1 ---------------------------------------------------------

CONNECT b_region1/b_region1
CREATE DATABASE LINK b_region1Tosystem
CONNECT TO system IDENTIFIED by fakepassword
using 'localhost:1521/XE';

---- Fragments Where (AlphaSort)

CREATE TABLE CLUBSPORTIF
AS select * FROM system.CLUBSPORTIF@b_region1Tosystem 
WHERE REGION ='Centre';

CREATE TABLE PERSONNEL
AS SELECT * FROM system.PERSONNEL@b_region1Tosystem
WHERE REGION = 'Centre';

CREATE TABLE STADE
AS SELECT * FROM system.STADE@b_region1Tosystem
WHERE REGION ='Centre';

---- Fragments Join (AlphaSort)

CREATE TABLE EQUIPE
AS SELECT S.CLUB, S.JOUEUR, DATEDEBUTCONTRAT, DATEFINCONTRAT, NUMEROMAILLOT, POSTE 
FROM system.EQUIPE@b_region1Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

CREATE TABLE JOUEUR
AS SELECT S.CODE, NOM, PRENOM, DATENAISSANCE, NATIONNALITE, POIDS, TAILLE, CLASSE
FROM system.JOUEUR@b_region1Tosystem S JOIN EQUIPE E ON S.CODE = E.JOUEUR;

CREATE TABLE PALMARES
AS SELECT P.CLUB, ANNEE, TROPHEE, NOMBREMATCHGAGNE, NOMBREMATCHPERDUS
FROM system.PALMARES@b_region1Tosystem P JOIN CLUBSPORTIF C ON P.CLUB = C.CODE;

CREATE TABLE STAFFTECHNIQUE
AS SELECT S.CODE, NOM, S.CLUB, FONCTION 
FROM system.STAFFTECHNIQUE@b_region1Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

-- BREGION2 ---------------------------------------------------------

CONNECT b_region2/b_region2
CREATE DATABASE LINK b_region2Tosystem
CONNECT TO system IDENTIFIED by fakepassword
using 'localhost:1521/XE';

---- Fragments Where (AlphaSort)

CREATE TABLE CLUBSPORTIF
AS select * FROM system.CLUBSPORTIF@b_region2Tosystem
WHERE REGION = 'Est';

CREATE TABLE PERSONNEL
AS SELECT * FROM system.PERSONNEL@b_region2Tosystem
WHERE REGION = 'Est';

CREATE TABLE STADE
AS SELECT * FROM system.STADE@b_region2Tosystem
WHERE REGION ='Est';

---- Fragments Join (AlphaSort)

CREATE TABLE EQUIPE
AS SELECT S.CLUB, S.JOUEUR, DATEDEBUTCONTRAT, DATEFINCONTRAT, NUMEROMAILLOT, POSTE 
FROM system.EQUIPE@b_region2Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

CREATE TABLE JOUEUR
AS SELECT S.CODE, NOM, PRENOM, DATENAISSANCE, NATIONNALITE, POIDS, TAILLE, CLASSE
FROM system.JOUEUR@b_region2Tosystem S JOIN EQUIPE E ON S.CODE = E.JOUEUR;

CREATE TABLE PALMARES
AS SELECT P.CLUB, ANNEE, TROPHEE, NOMBREMATCHGAGNE, NOMBREMATCHPERDUS
FROM system.PALMARES@b_region2Tosystem P JOIN CLUBSPORTIF C ON P.CLUB = C.CODE;

CREATE TABLE STAFFTECHNIQUE
AS SELECT S.CODE, NOM, S.CLUB, FONCTION 
FROM system.STAFFTECHNIQUE@b_region2Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

-- BREGION3 ---------------------------------------------------------

CONNECT b_region3/b_region3
CREATE DATABASE LINK b_region3Tosystem
CONNECT TO system IDENTIFIED by fakepassword
using 'localhost:1521/XE';

---- Fragments Where (AlphaSort)

CREATE TABLE CLUBSPORTIF
AS select * FROM system.CLUBSPORTIF@b_region3Tosystem
WHERE REGION = 'Ouest';

CREATE TABLE PERSONNEL
AS SELECT * FROM system.PERSONNEL@b_region3Tosystem
WHERE REGION = 'Ouest';

CREATE TABLE STADE
AS SELECT * FROM system.STADE@b_region3Tosystem
WHERE REGION ='Ouest';

---- Fragments Join (AlphaSort)

CREATE TABLE EQUIPE
AS SELECT S.CLUB, S.JOUEUR, DATEDEBUTCONTRAT, DATEFINCONTRAT, NUMEROMAILLOT, POSTE 
FROM system.EQUIPE@b_region3Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

CREATE TABLE JOUEUR
AS SELECT S.CODE, NOM, PRENOM, DATENAISSANCE, NATIONNALITE, POIDS, TAILLE, CLASSE
FROM system.JOUEUR@b_region3Tosystem S JOIN EQUIPE E ON S.CODE = E.JOUEUR;

CREATE TABLE PALMARES
AS SELECT P.CLUB, ANNEE, TROPHEE, NOMBREMATCHGAGNE, NOMBREMATCHPERDUS
FROM system.PALMARES@b_region3Tosystem P JOIN CLUBSPORTIF C ON P.CLUB = C.CODE;

CREATE TABLE STAFFTECHNIQUE
AS SELECT S.CODE, NOM, S.CLUB, FONCTION 
FROM system.STAFFTECHNIQUE@b_region3Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

-- BREGION4 ---------------------------------------------------------

CONNECT b_region4/b_region4
CREATE DATABASE LINK b_region4Tosystem
CONNECT TO system IDENTIFIED by fakepassword
using 'localhost:1521/XE';

---- Fragments Where (AlphaSort)

CREATE TABLE CLUBSPORTIF
AS select * FROM system.CLUBSPORTIF@b_region4Tosystem
WHERE REGION = 'Sud';

CREATE TABLE PERSONNEL
AS SELECT * FROM system.PERSONNEL@b_region4Tosystem
WHERE REGION = 'Sud';

CREATE TABLE STADE
AS SELECT * FROM system.STADE@b_region4Tosystem
WHERE REGION ='Sud';

---- Fragments Join (AlphaSort)

CREATE TABLE EQUIPE
AS SELECT S.CLUB, S.JOUEUR, DATEDEBUTCONTRAT, DATEFINCONTRAT, NUMEROMAILLOT, POSTE 
FROM system.EQUIPE@b_region4Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;

CREATE TABLE JOUEUR
AS SELECT S.CODE, NOM, PRENOM, DATENAISSANCE, NATIONNALITE, POIDS, TAILLE, CLASSE
FROM system.JOUEUR@b_region4Tosystem S JOIN EQUIPE E ON S.CODE = E.JOUEUR;

CREATE TABLE PALMARES
AS SELECT P.CLUB, ANNEE, TROPHEE, NOMBREMATCHGAGNE, NOMBREMATCHPERDUS
FROM system.PALMARES@b_region4Tosystem P JOIN CLUBSPORTIF C ON P.CLUB = C.CODE;

CREATE TABLE STAFFTECHNIQUE
AS SELECT S.CODE, NOM, S.CLUB, FONCTION 
FROM system.STAFFTECHNIQUE@b_region4Tosystem S JOIN CLUBSPORTIF C ON S.CLUB = C.CODE;