-- Master VIEWS -----------------------------------------------------------------

CONNECT b_master/b_master

CREATE OR REPLACE VIEW B_MASTER.Club_Global AS
    SELECT * FROM B_MASTER.CLUBSPORTIF
    UNION ALL
    SELECT * FROM B_REGION1.CLUBSPORTIF
    UNION ALL
    SELECT * FROM B_REGION2.CLUBSPORTIF
    UNION ALL
    SELECT * FROM B_REGION3.CLUBSPORTIF
    UNION ALL
    SELECT * FROM B_REGION4.CLUBSPORTIF;

CREATE OR REPLACE VIEW B_MASTER.Personnel_Global AS
    SELECT * FROM B_MASTER.PERSONNEL
    UNION ALL
    SELECT * FROM B_REGION1.PERSONNEL
    UNION ALL
    SELECT * FROM B_REGION2.PERSONNEL
    UNION ALL
    SELECT * FROM B_REGION3.PERSONNEL
    UNION ALL
    SELECT * FROM B_REGION4.PERSONNEL;

CREATE OR REPLACE VIEW B_MASTER.Palmares_Global AS
    SELECT * FROM B_MASTER.PALMARES
    UNION ALL
    SELECT * FROM B_REGION1.PALMARES
    UNION ALL
    SELECT * FROM B_REGION2.PALMARES
    UNION ALL
    SELECT * FROM B_REGION3.PALMARES
    UNION ALL
    SELECT * FROM B_REGION4.PALMARES;

CREATE OR REPLACE VIEW B_MASTER.Staff_Technique_Global AS
    SELECT * FROM B_MASTER.STAFFTECHNIQUE
    UNION ALL
    SELECT * FROM B_REGION1.STAFFTECHNIQUE
    UNION ALL
    SELECT * FROM B_REGION2.STAFFTECHNIQUE
    UNION ALL
    SELECT * FROM B_REGION3.STAFFTECHNIQUE
    UNION ALL
    SELECT * FROM B_REGION4.STAFFTECHNIQUE;

CREATE OR REPLACE VIEW B_MASTER.Joueur_Global AS
    SELECT * FROM B_MASTER.JOUEUR
    UNION ALL
    SELECT * FROM B_REGION1.JOUEUR
    UNION ALL
    SELECT * FROM B_REGION2.JOUEUR
    UNION ALL
    SELECT * FROM B_REGION3.JOUEUR
    UNION ALL
    SELECT * FROM B_REGION4.JOUEUR;

CREATE OR REPLACE VIEW B_MASTER.Stade_Global AS
    SELECT * FROM B_MASTER.STADE
    UNION ALL
    SELECT * FROM B_REGION1.STADE
    UNION ALL
    SELECT * FROM B_REGION2.STADE
    UNION ALL
    SELECT * FROM B_REGION3.STADE
    UNION ALL
    SELECT * FROM B_REGION4.STADE;

CREATE OR REPLACE VIEW B_MASTER.Calendrier AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL WHERE (CLUBA IN (SELECT CODE FROM CLUBSPORTIF)) OR (CLUBB IN (SELECT CODE FROM CLUBSPORTIF));


CREATE OR REPLACE VIEW B_MASTER.STATISTIQUE_SPECTATEUR AS
SELECT BUREAU.REGION, AVG(MATCH_GLOBAL.NBRESPECTATEURS) AS TOTAL_SPECTATEURS
FROM BUREAU
JOIN Stade_Global ON BUREAU.REGION = Stade_Global.REGION
JOIN MATCH_GLOBAL ON Stade_Global.CODE = MATCH_GLOBAL.STADE
GROUP BY BUREAU.REGION;

CREATE OR REPLACE VIEW B_MASTER.STATISTIQUE_BUTS
AS SELECT BUREAU.REGION,CALENDRIER_GLOBAL.CLUBA AS CLUB ,MATCH_GLOBAL.NBREBUTCLUBA AS BUTS_MARQUES
FROM BUREAU
JOIN STADE_GLOBAL ON BUREAU.REGION = STADE_GLOBAL.REGION
JOIN CALENDRIER_GLOBAL ON STADE_GLOBAL.CODE = CALENDRIER_GLOBAL.STADE
JOIN MATCH_GLOBAL ON CALENDRIER_GLOBAL.MATCH = MATCH_GLOBAL.CODE
UNION ALL 
SELECT BUREAU.REGION,CALENDRIER_GLOBAL.CLUBB AS CLUB ,MATCH_GLOBAL.NBREBUTCLUBB AS BUTS_MARQUES
FROM BUREAU
JOIN STADE_GLOBAL ON BUREAU.REGION = STADE_GLOBAL.REGION
JOIN CALENDRIER_GLOBAL ON STADE_GLOBAL.CODE = CALENDRIER_GLOBAL.STADE
JOIN MATCH_GLOBAL ON CALENDRIER_GLOBAL.MATCH = MATCH_GLOBAL.CODE;

CREATE OR REPLACE VIEW B_MASTER.STATISTIQUE_RESULTAT_MATCH AS
    SELECT MATCH_GLOBAL.CODE,
       CASE
           WHEN NBREBUTCLUBA > NBREBUTCLUBB THEN CLUBA
           WHEN NBREBUTCLUBB > NBREBUTCLUBA THEN CLUBB
           ELSE 'Egalite'
       END AS Gagnant
    FROM MATCH_GLOBAL
    INNER JOIN B_MASTER.CALENDRIER_GLOBAL
        ON B_MASTER.CALENDRIER_GLOBAL.MATCH = B_MASTER.MATCH_GLOBAL.CODE;

CREATE OR REPLACE VIEW B_MASTER.STATISTIQUE_PALMARES AS
      SELECT
          GAGNANT,
          COUNT(*) AS NB_MATCH_GAGNE
      FROM STATISTIQUE_RESULTAT_MATCH
      WHERE GAGNANT != 'Egalite'
      GROUP BY GAGNANT;
      
-- Region 1 VIEWS -----------------------------------------------------------------

CONNECT b_region1/b_region1
CREATE OR REPLACE VIEW B_REGION1.Club_Global AS SELECT * FROM B_MASTER.Club_Global;
CREATE OR REPLACE VIEW B_REGION1.Personnel_Global AS SELECT * FROM B_MASTER.Personnel_Global;
CREATE OR REPLACE VIEW B_REGION1.Palmares_Global AS SELECT * FROM B_MASTER.Palmares_Global;
CREATE OR REPLACE VIEW B_REGION1.Staff_Technique_Global AS SELECT * FROM B_MASTER.Staff_Technique_Global;
CREATE OR REPLACE VIEW B_REGION1.Joueur_Global AS SELECT * FROM B_MASTER.Joueur_Global;
CREATE OR REPLACE VIEW B_REGION1.Calendrier AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region1Tob_master WHERE (CLUBA IN (SELECT CODE FROM CLUBSPORTIF)) OR (CLUBB IN (SELECT CODE FROM CLUBSPORTIF));
CREATE OR REPLACE VIEW B_REGION1.Calendrier_Global AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region1Tob_master;

-- Region 2 VIEWS -----------------------------------------------------------------

CONNECT b_region2/b_region2
CREATE OR REPLACE VIEW B_REGION2.Club_Global AS SELECT * FROM B_MASTER.Club_Global;
CREATE OR REPLACE VIEW B_REGION2.Personnel_Global AS SELECT * FROM B_MASTER.Personnel_Global;
CREATE OR REPLACE VIEW B_REGION2.Palmares_Global AS SELECT * FROM B_MASTER.Palmares_Global;
CREATE OR REPLACE VIEW B_REGION2.Joueur_Global AS SELECT * FROM B_MASTER.Joueur_Global;
CREATE OR REPLACE VIEW B_REGION2.Staff_Technique_Global AS SELECT * FROM B_MASTER.Staff_Technique_Global;
CREATE OR REPLACE VIEW B_REGION2.Calendrier AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region2Tob_master WHERE (CLUBA IN (SELECT CODE FROM CLUBSPORTIF)) OR (CLUBB IN (SELECT CODE FROM CLUBSPORTIF));
CREATE OR REPLACE VIEW B_REGION2.Calendrier_Global AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region2Tob_master;

-- Region 3 VIEWS -----------------------------------------------------------------

CONNECT b_region3/b_region3
CREATE OR REPLACE VIEW B_REGION3.Club_Global AS SELECT * FROM B_MASTER.Club_Global;
CREATE OR REPLACE VIEW B_REGION3.Personnel_Global AS SELECT * FROM B_MASTER.Personnel_Global;
CREATE OR REPLACE VIEW B_REGION3.Palmares_Global AS SELECT * FROM B_MASTER.Palmares_Global;
CREATE OR REPLACE VIEW B_REGION3.Staff_Technique_Global AS SELECT * FROM B_MASTER.Staff_Technique_Global;
CREATE OR REPLACE VIEW B_REGION3.Joueur_Global AS SELECT * FROM B_MASTER.Joueur_Global;
CREATE OR REPLACE VIEW B_REGION3.Calendrier AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region3Tob_master WHERE (CLUBA IN (SELECT CODE FROM CLUBSPORTIF)) OR (CLUBB IN (SELECT CODE FROM CLUBSPORTIF));
CREATE OR REPLACE VIEW B_REGION3.Calendrier_Global AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region3Tob_master;

-- Region 4 VIEWS -----------------------------------------------------------------

CONNECT b_region4/b_region4
CREATE OR REPLACE VIEW B_REGION4.Club_Global AS SELECT * FROM B_MASTER.Club_Global;
CREATE OR REPLACE VIEW B_REGION4.Personnel_Global AS SELECT * FROM B_MASTER.Personnel_Global;
CREATE OR REPLACE VIEW B_REGION4.Palmares_Global AS SELECT * FROM B_MASTER.Palmares_Global;
CREATE OR REPLACE VIEW B_REGION4.Joueur_Global AS SELECT * FROM B_MASTER.Joueur_Global;
CREATE OR REPLACE VIEW B_REGION4.Staff_Technique_Global AS SELECT * FROM B_MASTER.Staff_Technique_Global;
CREATE OR REPLACE VIEW B_REGION4.Calendrier AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region4Tob_master WHERE (CLUBA IN (SELECT CODE FROM CLUBSPORTIF)) OR (CLUBB IN (SELECT CODE FROM CLUBSPORTIF));
CREATE OR REPLACE VIEW B_REGION4.Calendrier_Global AS SELECT * FROM B_MASTER.CALENDRIER_GLOBAL@b_region4Tob_master;